spring:
  application:
    name: ecb-exchange-service
#server:
#  port: 9000

management:
  server:
    port: 9001
  endpoint:
    health:
      show-details: always

client:
  ecb:
    daily-rate-uri: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml
    root-element: gesmes:Envelope
    data-element: Cube
    rate: rate
    currency: currency
    base-currency: EUR
    graph: https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/eurofxref-graph-%s.en.html
