spring:
  datasource:
    url: jdbc:h2:mem:fes
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

  #server:
#  port: 9000
management:
  server:
    port: 9001
  endpoint:
    health:
      show-details: always

provider:
  api:
    schedule:
      frequency: "*/1 * * * * *"
    fetch-events:
      uri: https://provider.code-challenge.feverup.com/api/events
      root-node: eventList
      output-node: output
      base-event-node: base_event
      event-node: event